### PR TITLE
Show an error message if fetching fails

### PR DESCRIPTION
**Pull request by tsdko**
When I first tried to scrape, I got an error that's not very informative:

```
Traceback (most recent call last):
  File "Scraper.py", line 69, in <module>
    for i in range(config.start_entry, nt.last_entry + 1):
  File "/home/flan/.src/nyaamagnet/Nyaa.py", line 14, in last_entry
    link = soup.find('tr', class_='tlistrow').find('td', class_='tlistname').a['href']
AttributeError: 'NoneType' object has no attribute 'find'
```

### CODE REVIEW

**Comment by Hamuko** [comment]
While that error tells that you are having issues reaching Nyaa, I still have my doubts about the validity of that error message. I got it earlier when scraping Sukebei on my server and I couldn't reach it at all on it. However, I was able to reach it on my home machine, which has a separate IP. And now it seems like my home machine is also unable to access the site, even though I can still access it with my phone's 3G connection.

Not exactly sure why Sukebei is blocking IPs that have scraped the site when Nyaa doesn't, but it doesn't seem like it's because Nyaa is down.

Also, is there a benefit to `sys.exit(1)` as opposed to `exit(code=1)`?

**Comment by tsdko** [comment]
You're right, I get 524 only on my home connection. Haven't noticed that.

> Also, is there a benefit to `sys.exit(1)` as opposed to `exit(code=1)`?

There's no difference between them as far as I know. I used `sys.exit(1)` because sys is used anyway in `print()` to redirect the message to stderr.

**Comment by Hamuko** [comment]
Cloudflare gives me Error 522 when I try to access Sukebei. Nothing when I try to access Nyaa though. Unsure if it's related to the new DDoS protection. I planned on asking on the IRC channel, but apparently I'm banned from that as well. Didn't even know I had visited it.

**Comment by tsdko** [comment]
I get 524 on both Sukebei and Nyaa.

**Comment by Hamuko** [comment]
That's really odd, since I haven't gotten Nyaa blocked on either connection. And I've had my server scraping Nyaa for quite a while now. Maybe you should ask someone in the know about it.

**Pull request merged**
